CREATE TABLE IF NOT EXISTS tokos (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  name VARCHAR(255) NOT NULL,
  token VARCHAR(255) NOT NULL,
  charge INT NOT NULL DEFAULT 2,
  callback_url VARCHAR(255) NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uniq_tokos_token (token),
  KEY idx_tokos_name (name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS balances (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  toko_id BIGINT UNSIGNED NOT NULL,
  pending DECIMAL(15,2) NOT NULL DEFAULT 0.00,
  available DECIMAL(15,2) NOT NULL DEFAULT 0.00,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uniq_balances_toko_id (toko_id),
  CONSTRAINT fk_balances_toko FOREIGN KEY (toko_id) REFERENCES tokos(id) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS transactions (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  toko_id BIGINT UNSIGNED NOT NULL,
  player VARCHAR(255) NULL,
  code VARCHAR(255) NULL,
  `type` ENUM('deposit', 'withdraw') NOT NULL DEFAULT 'deposit',
  status ENUM('pending', 'success', 'failed') NOT NULL,
  barcode TEXT NULL,
  reference VARCHAR(255) NULL,
  amount BIGINT UNSIGNED NOT NULL,
  fee_withdrawal BIGINT UNSIGNED NULL,
  netto BIGINT UNSIGNED NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_transactions_toko_id (toko_id),
  KEY idx_transactions_status (status),
  KEY idx_transactions_type (`type`),
  KEY idx_transactions_reference (reference),
  CONSTRAINT fk_transactions_toko FOREIGN KEY (toko_id) REFERENCES tokos(id) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS toko_users (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  user_id BIGINT UNSIGNED NOT NULL,
  toko_id BIGINT UNSIGNED NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uniq_toko_users_user_toko (user_id, toko_id),
  KEY idx_toko_users_user_id (user_id),
  KEY idx_toko_users_toko_id (toko_id),
  CONSTRAINT fk_toko_users_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_toko_users_toko FOREIGN KEY (toko_id) REFERENCES tokos(id) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS payments (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  bank_code VARCHAR(10) NOT NULL,
  bank_name VARCHAR(255) NOT NULL,
  bank_swift_code VARCHAR(255) NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_payments_bank_code (bank_code),
  KEY idx_payments_bank_name (bank_name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
